version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: fastapi_tm_rabbitmq
    hostname: fastapi_tm_rabbitmq
    networks:
      dev_net:
        ipv4_address: "172.20.5.5"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  redis:
    image: redis:6.2-alpine
    container_name: fastapi_tm_redis
    networks:
      dev_net:
        ipv4_address: "172.20.5.6"
    command: redis-server --requirepass 12345678
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/redis/data:/data

  celery_services:
    image: "celery_services:latest"
    container_name: celery_services
    build:
      context: "./celery_services"
      dockerfile: ./Dockerfile
    command: /bin/bash ./docker-entrypoint.sh
    networks:
      dev_net:
        ipv4_address: 172.20.5.11
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./celery_services:/home/project
      - ./conf/celery_services/product.local.toml:/home/project/conf/product.local.toml
      - ./conf/celery_services/test.local.toml:/home/project/conf/test.local.toml
      - ./conf/celery_services/docker-entrypoint.sh:/home/project/docker-entrypoint.sh
      - ./logs/celery_services:/home/logs
    depends_on:
      - redis
      - rabbitmq

networks:
  dev_net:
    external: true
