version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: fastapi_tm_rabbitmq
    restart: always
    hostname: fastapi_tm_rabbitmq
    networks:
      dev_net:
        ipv4_address: "172.20.5.5"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/fastapi_tm_rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  redis:
    image: redis:6.2-alpine
    container_name: fastapi_tm_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: always
    networks:
      dev_net:
        ipv4_address: "172.20.5.6"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/fastapi_tm_redis/redis.conf:/etc/redis/redis.conf
      # - ./conf/redis/tls:/tls
      - ./data/fastapi_tm_redis/data:/data

  celery:
    image: "fastapi_tm_celery:latest"
    container_name: fastapi_tm_celery
    build: "./fastapi_tm_celery"
    command: ["/bin/bash", "./docker-entrypoint.sh"]
    restart: always
    networks:
      dev_net:
        ipv4_address: "172.20.5.11"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./fastapi_tm_celery:/home/project
      - ./conf/fastapi_tm_celery/product.local.toml:/home/project/conf/product.local.toml
      - ./conf/fastapi_tm_celery/test.local.toml:/home/project/conf/test.local.toml
      - ./conf/fastapi_tm_celery/docker-entrypoint.sh:/home/project/docker-entrypoint.sh
      - ./logs/fastapi_tm_celery:/home/logs
    depends_on:
      - redis
      - rabbitmq

networks:
  dev_net:
    external: true
